# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: quizapp_development

test:
  <<: *default
  database: quizapp_test

production:
  primary: &primary_production
    <<: *default
    database: quizapp_production
  cache:
    <<: *primary_production
    database: quizapp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: quizapp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: quizapp_production_cable
    migrations_paths: db/cable_migrate
