name: Deploy Rails App to Azure Web App

permissions:
  id-token: write  # Berechtigung zum Schreiben des ID-Tokens
  contents: write  # Berechtigung zum Lesen des Repository-Inhalts

on:
  push:
    branches:
      - Azure-connect

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: yarn install

      # Azure login action using Service Principal credentials
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          environment: azurecloud

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Quizapp
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
