name: Deploy Rails App to Azure Web App

permissions:
  id-token: write  # Berechtigung zum Schreiben des ID-Tokens
  contents: write  # Berechtigung zum Lesen des Repository-Inhalts

on:
  push:
    branches:
      - Azure-connect

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: yarn install


      # Check out the repo
      - uses: actions/checkout@main
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      # Set up .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using Azure Credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_QUIZAPP }} # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      
      - name: logout
        run: |
          az logout
