name: Deploy Rails App to Azure Web App

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - Azure-connect

env:
  RAILS_ENV: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3

      - name: Set up Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          yarn install

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Quizapp   # Dein Azure App Service Name
          package: .          # Root-Verzeichnis deiner App

      - name: Logout of Azure
        run: az logout
