name: Deploy Rails App to Azure Web App

on:
  push:
    branches:
      - Azure-connect

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install

# Azure login action
- name: Login to Azure
  uses: azure/login@v1
  with:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Quizapp
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
