name: Auto-Deploy to Azure Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: SSH into Azure VM and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}  # Stellt sicher, dass der Host korrekt geladen wird!
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/quizapp/code
          git pull origin main
          export DB_PASSWORD=PnSulZMF6HkerC7vFQ8V
          export GEM_HOME="$HOME/.gem"
          RAILS_ENV=production bundle install
          RAILS_ENV=productionrails assets:precompile
          RAILS_ENV=production rails db:migrate
          sudo systemctl restart nginx
          passenger stop
          passenger start
