name: Build and deploy Ruby on Rails app to Azure Web App - Quizapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Passe das ggf. an deine Ruby-Version an

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Node.js (für JS/CSS Assets)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS dependencies
        run: |
          yarn install || npm install

      - name: Precompile assets
        run: bundle exec rake assets:precompile

      - name: Setup DB (optional, falls du keine externe DB nutzt, kannst du das auskommentieren)
        run: |
          cp config/database.yml.github config/database.yml || echo "using env/database url"
          bundle exec rake db:migrate

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Quizapp' # Dein Azure App Service Name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7052853CDF584B0BBE7F3024D1206CD2 }}
          package: .
